name: Build and Push Docker Image

on:
  push:
    branches:
      - dockerize_with_alpine_opt
  pull_request:
    branches:
      - dockerize_with_alpine_opt

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Run cargo vendor
      run: |
        cargo install cargo-vendor
        cargo vendor

    - name: Login to DockerHub
      if: github.event_name == 'push' && github.ref == 'refs/heads/dockerize_with_alpine_opt'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/dockerize_with_alpine_opt' }}
        tags: will8clark/fork-observer-alpine:latest
